### ISSUE TITLE
Remove Arrows and Bolts entirely

### ISSUE THREAD

**Issue by tunbridgep** [eqNj/eqN-PD2-Filter#1]
Season 3 made Arrows and Bolts completely useless as they aren't needed anymore, since Season 3 made them infinite.

**Comment by eqNj** [comment]
Actually, they've been infinite since Season 1 of PD2. While I understand there is little point in ever seeing them, rest assured: Arrows and Bolts only show on the ground from character level 1 up until character level 7. This is so that switching to your first rare weapon, if a bow or crossbow for extremely early leveling, is easily doable.

**Comment by eqNj** [comment]
Notable, as of season 4 magic arrows and bolts will show on less strict filter levels if playing Amazon, while rare arrows and bolts will always show for all classes and be lightly highlighted for Amazons.
